---
title: "upas india"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
  library(ggmap)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  source("upas_functions.R")
```

# Load upas data

* Load data
* Save to file

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  upas <- load_multifile("data/log", "*")
	saveRDS(data, "upas_india.rds")
```

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  head(upas, 2)
```

# Clean data

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
   upas <- dplyr::filter(upas, sample != "BLR01 ")
   upas <- gps_clean(upas)
```

# Plot data

* Map

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=8}
  box <- make_bbox(gps_lon, gps_lat, upas)

  map <- qmap(c(lon = mean(upas$gps_lon, na.rm = TRUE),
                lat = mean(upas$gps_lat, na.rm = TRUE)),
                zoom = calc_zoom(box) -2)

  map + geom_path(aes(y = gps_lat, x = gps_lon, colour = sample, size = "1"), data = upas)
```

* Flow

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=8}
  ggplot(upas, aes(x= datetime, y = flow, group = sample, colour = sample)) +
    geom_point() +
    theme_minimal()
```

* Temperature

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=8}
  ggplot(upas, aes(x= datetime, y = t_oc, group = sample, colour = sample)) +
    geom_point() +
    theme_minimal()
```

* Atmos Pressure

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=8}
  ggplot(upas, aes(x= datetime, y = p_kpa, group = sample, colour = sample)) +
    geom_point() +
    theme_minimal()
```

* Relative humidity

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=8}
  ggplot(upas, aes(x= datetime, y = rh_pct, group = sample, colour = sample)) +
    geom_point() +
    theme_minimal()
```

* Delta p

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=8}
  ggplot(upas, aes(x= datetime, y = dp, group = sample, colour = sample)) +
    geom_point() +
    theme_minimal()
```

* battery voltage

```{r, echo=TRUE, warning=FALSE, message=FALSE, results='markup', cache=FALSE, fig.width=12, fig.height=8}
  ggplot(upas, aes(x= datetime, y = bat_v, group = sample, colour = sample)) +
    geom_point() +
    theme_minimal()
```

